name: Start Linux AWS server

on:
 # Triggers the workflow on push or pull request events but only for the master branch
 # push:
 #   branches: [ master ]
 # pull_request:
 #   branches: [ master ]
 # вместо тригеров, рабочий процесс workflow будет запускаться вручную
  workflow_dispatch: # Allows to run this workflow manually from the Actions tab

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    #build: # This workflow contains a single job called "build"
    terraform-actions:
    name: Workflow
    runs-on: ubuntu-latest # The type of runner that the job will run on
    
    steps: # Steps represent a sequence of tasks that will be executed as part of the job
      - name: Checkout Repository
      - uses: actions/checkout@v2  # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
