name: Learn_start_Directory
on: #workflow_dispatch
  push: 
    branches: 
      - master
jobs:    
  terraform_actions:            
    name: Запускаем контейнер с машиной
    runs-on: ubuntu-latest   

    steps:                     
      - name: Checkout-клонирование Repository в контейненр с машиной                          
        uses: actions/checkout@v2                                                             #--default = $ GITHUB_WORKSPACE
#      - name: Путь для действия "клонирования в контейнер"
#        uses: /ildarbiano/iaac/linux@master     #---Error: Can't find 'action.yml', 'action.yaml' or 'Dockerfile' under '/home/runner/work/_actions/ildarbiano/iaac/master/linux'. Did you forget to run actions/checkout before running your local action?
#        uses: ./linux                           #---Error: Can't find 'action.yml', 'action.yaml' or 'Dockerfile' under '/home/runner/work/iaac/iaac/linux'. Did you forget to run actions/checkout before running your local action?
        with: 
#        path:
#        repository: '$ {{github.repository}}'
#          repository: ildarbiano/iaac/linux     #---Error: Invalid repository 'ildarbiano/iaac/linux'. Expected format {owner}/{repo}.
          path: linux                            #---ошибки нет, но и содержимого директории linux не показывает/видит
      - name: Проверяем, что видит github и какой terraform может обрабатывать
        run: ls -la

#    - name: Проверяет/Запрашивает AWS Credentials
#      uses: aws-actions/configure-aws-credentials@v1         
#      with:
#        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#        aws-region: ${{ secrets.AWS_REGION }}
      
#    - name: Setup настройка Terraform
#      uses: hashicorp/setup-terraform@v1
#      with:
#        terraform_version: 0.12.8
#        repository: "${{ github.repository }}/linux"                                           #---зачем?
