name: Work_with_Other_Repo
on:
  push: 
    branches: 
      - master 

jobs:
  See_Prefix_Linux:           
    name: Изучаем видимость
    runs-on: ubuntu-latest                      # The type of runner that the job will run on
#    env: 
#     working-directory: '/home/runner/work/iaac/iaac/linux/'
    steps:                                      # Steps represent a sequence of tasks that will be executed as part of the job
    - name: Checkout another Repository                       
      uses: actions/checkout@v2                 #--Проверяет репозиторий, чтобы Job могла получить к нему доступ
      with:
       repository: ildarbiano/static_files      #--Рабочий переход в другой репозиторий
#        path: /home/runner/work/iaac/iaac/linux
#        repository: '$ {{github.repository}}' 
#    - name: Путь для действия "клонирования в контейнер"
#      uses: '/home/runner/work/iaac/iaac/linux'

    - name: List another Repo
      run: ls -la
 

