name: Terraform apply

on:
  workflow_dispatch:

jobs:
  terraform-actions:
    name: Workflow
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repository
      uses: actions/checkout@master

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.12.8

    - name: Terraform Init            #---Если вы не укажете, в качестве name-имени шага по умолчанию будет использоваться текст, указанный в run-команде
      id: init                        #---идентификатор для ссылки на step в контексте кода
      run: terraform init
      continue-on-error: true         #---true - разрешит выполнение задания при сбое этого шага

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color   #--- -no-color????????????
      continue-on-error: true

    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color
      continue-on-error: true


    - name: Terraform Apply
      id: apply
      run: terraform apply -auto-approve -no-color      #--- -auto-approve -no-color????????????????
      continue-on-error: true
